//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaWebApp.TiendaServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://tempuri.org/", ItemName="int")]
    [System.SerializableAttribute()]
    public class ArrayOfInt : System.Collections.Generic.List<int> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TiendaServiceReference.Service1Soap")]
    public interface Service1Soap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        TiendaWebApp.TiendaServiceReference.HelloWorldResponse HelloWorld(TiendaWebApp.TiendaServiceReference.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name getAllProductsNamesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAllProductsNames", ReplyAction="*")]
        TiendaWebApp.TiendaServiceReference.getAllProductsNamesResponse getAllProductsNames(TiendaWebApp.TiendaServiceReference.getAllProductsNamesRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExistProduct", ReplyAction="*")]
        TiendaWebApp.TiendaServiceReference.ExistProductResponse ExistProduct(TiendaWebApp.TiendaServiceReference.ExistProductRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getProductID", ReplyAction="*")]
        TiendaWebApp.TiendaServiceReference.getProductIDResponse getProductID(TiendaWebApp.TiendaServiceReference.getProductIDRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getProductSells", ReplyAction="*")]
        TiendaWebApp.TiendaServiceReference.getProductSellsResponse getProductSells(TiendaWebApp.TiendaServiceReference.getProductSellsRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getProductAverageSells", ReplyAction="*")]
        TiendaWebApp.TiendaServiceReference.getProductAverageSellsResponse getProductAverageSells(TiendaWebApp.TiendaServiceReference.getProductAverageSellsRequest request);
        
        // CODEGEN: Generating message contract since element name itemID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FormatoCorrecto", ReplyAction="*")]
        TiendaWebApp.TiendaServiceReference.FormatoCorrectoResponse FormatoCorrecto(TiendaWebApp.TiendaServiceReference.FormatoCorrectoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public TiendaWebApp.TiendaServiceReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(TiendaWebApp.TiendaServiceReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public TiendaWebApp.TiendaServiceReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(TiendaWebApp.TiendaServiceReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllProductsNamesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllProductsNames", Namespace="http://tempuri.org/", Order=0)]
        public TiendaWebApp.TiendaServiceReference.getAllProductsNamesRequestBody Body;
        
        public getAllProductsNamesRequest() {
        }
        
        public getAllProductsNamesRequest(TiendaWebApp.TiendaServiceReference.getAllProductsNamesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getAllProductsNamesRequestBody {
        
        public getAllProductsNamesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllProductsNamesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllProductsNamesResponse", Namespace="http://tempuri.org/", Order=0)]
        public TiendaWebApp.TiendaServiceReference.getAllProductsNamesResponseBody Body;
        
        public getAllProductsNamesResponse() {
        }
        
        public getAllProductsNamesResponse(TiendaWebApp.TiendaServiceReference.getAllProductsNamesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getAllProductsNamesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TiendaWebApp.TiendaServiceReference.ArrayOfString getAllProductsNamesResult;
        
        public getAllProductsNamesResponseBody() {
        }
        
        public getAllProductsNamesResponseBody(TiendaWebApp.TiendaServiceReference.ArrayOfString getAllProductsNamesResult) {
            this.getAllProductsNamesResult = getAllProductsNamesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExistProductRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExistProduct", Namespace="http://tempuri.org/", Order=0)]
        public TiendaWebApp.TiendaServiceReference.ExistProductRequestBody Body;
        
        public ExistProductRequest() {
        }
        
        public ExistProductRequest(TiendaWebApp.TiendaServiceReference.ExistProductRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ExistProductRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public ExistProductRequestBody() {
        }
        
        public ExistProductRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExistProductResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExistProductResponse", Namespace="http://tempuri.org/", Order=0)]
        public TiendaWebApp.TiendaServiceReference.ExistProductResponseBody Body;
        
        public ExistProductResponse() {
        }
        
        public ExistProductResponse(TiendaWebApp.TiendaServiceReference.ExistProductResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ExistProductResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ExistProductResult;
        
        public ExistProductResponseBody() {
        }
        
        public ExistProductResponseBody(bool ExistProductResult) {
            this.ExistProductResult = ExistProductResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getProductIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getProductID", Namespace="http://tempuri.org/", Order=0)]
        public TiendaWebApp.TiendaServiceReference.getProductIDRequestBody Body;
        
        public getProductIDRequest() {
        }
        
        public getProductIDRequest(TiendaWebApp.TiendaServiceReference.getProductIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getProductIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public getProductIDRequestBody() {
        }
        
        public getProductIDRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getProductIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getProductIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public TiendaWebApp.TiendaServiceReference.getProductIDResponseBody Body;
        
        public getProductIDResponse() {
        }
        
        public getProductIDResponse(TiendaWebApp.TiendaServiceReference.getProductIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getProductIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getProductIDResult;
        
        public getProductIDResponseBody() {
        }
        
        public getProductIDResponseBody(string getProductIDResult) {
            this.getProductIDResult = getProductIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getProductSellsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getProductSells", Namespace="http://tempuri.org/", Order=0)]
        public TiendaWebApp.TiendaServiceReference.getProductSellsRequestBody Body;
        
        public getProductSellsRequest() {
        }
        
        public getProductSellsRequest(TiendaWebApp.TiendaServiceReference.getProductSellsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getProductSellsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public getProductSellsRequestBody() {
        }
        
        public getProductSellsRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getProductSellsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getProductSellsResponse", Namespace="http://tempuri.org/", Order=0)]
        public TiendaWebApp.TiendaServiceReference.getProductSellsResponseBody Body;
        
        public getProductSellsResponse() {
        }
        
        public getProductSellsResponse(TiendaWebApp.TiendaServiceReference.getProductSellsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getProductSellsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TiendaWebApp.TiendaServiceReference.ArrayOfInt getProductSellsResult;
        
        public getProductSellsResponseBody() {
        }
        
        public getProductSellsResponseBody(TiendaWebApp.TiendaServiceReference.ArrayOfInt getProductSellsResult) {
            this.getProductSellsResult = getProductSellsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getProductAverageSellsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getProductAverageSells", Namespace="http://tempuri.org/", Order=0)]
        public TiendaWebApp.TiendaServiceReference.getProductAverageSellsRequestBody Body;
        
        public getProductAverageSellsRequest() {
        }
        
        public getProductAverageSellsRequest(TiendaWebApp.TiendaServiceReference.getProductAverageSellsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getProductAverageSellsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public getProductAverageSellsRequestBody() {
        }
        
        public getProductAverageSellsRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getProductAverageSellsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getProductAverageSellsResponse", Namespace="http://tempuri.org/", Order=0)]
        public TiendaWebApp.TiendaServiceReference.getProductAverageSellsResponseBody Body;
        
        public getProductAverageSellsResponse() {
        }
        
        public getProductAverageSellsResponse(TiendaWebApp.TiendaServiceReference.getProductAverageSellsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getProductAverageSellsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public float getProductAverageSellsResult;
        
        public getProductAverageSellsResponseBody() {
        }
        
        public getProductAverageSellsResponseBody(float getProductAverageSellsResult) {
            this.getProductAverageSellsResult = getProductAverageSellsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FormatoCorrectoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FormatoCorrecto", Namespace="http://tempuri.org/", Order=0)]
        public TiendaWebApp.TiendaServiceReference.FormatoCorrectoRequestBody Body;
        
        public FormatoCorrectoRequest() {
        }
        
        public FormatoCorrectoRequest(TiendaWebApp.TiendaServiceReference.FormatoCorrectoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FormatoCorrectoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string itemID;
        
        public FormatoCorrectoRequestBody() {
        }
        
        public FormatoCorrectoRequestBody(string itemID) {
            this.itemID = itemID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FormatoCorrectoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FormatoCorrectoResponse", Namespace="http://tempuri.org/", Order=0)]
        public TiendaWebApp.TiendaServiceReference.FormatoCorrectoResponseBody Body;
        
        public FormatoCorrectoResponse() {
        }
        
        public FormatoCorrectoResponse(TiendaWebApp.TiendaServiceReference.FormatoCorrectoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FormatoCorrectoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FormatoCorrectoResult;
        
        public FormatoCorrectoResponseBody() {
        }
        
        public FormatoCorrectoResponseBody(string FormatoCorrectoResult) {
            this.FormatoCorrectoResult = FormatoCorrectoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : TiendaWebApp.TiendaServiceReference.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<TiendaWebApp.TiendaServiceReference.Service1Soap>, TiendaWebApp.TiendaServiceReference.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TiendaWebApp.TiendaServiceReference.HelloWorldResponse TiendaWebApp.TiendaServiceReference.Service1Soap.HelloWorld(TiendaWebApp.TiendaServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            TiendaWebApp.TiendaServiceReference.HelloWorldRequest inValue = new TiendaWebApp.TiendaServiceReference.HelloWorldRequest();
            inValue.Body = new TiendaWebApp.TiendaServiceReference.HelloWorldRequestBody();
            TiendaWebApp.TiendaServiceReference.HelloWorldResponse retVal = ((TiendaWebApp.TiendaServiceReference.Service1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TiendaWebApp.TiendaServiceReference.getAllProductsNamesResponse TiendaWebApp.TiendaServiceReference.Service1Soap.getAllProductsNames(TiendaWebApp.TiendaServiceReference.getAllProductsNamesRequest request) {
            return base.Channel.getAllProductsNames(request);
        }
        
        public TiendaWebApp.TiendaServiceReference.ArrayOfString getAllProductsNames() {
            TiendaWebApp.TiendaServiceReference.getAllProductsNamesRequest inValue = new TiendaWebApp.TiendaServiceReference.getAllProductsNamesRequest();
            inValue.Body = new TiendaWebApp.TiendaServiceReference.getAllProductsNamesRequestBody();
            TiendaWebApp.TiendaServiceReference.getAllProductsNamesResponse retVal = ((TiendaWebApp.TiendaServiceReference.Service1Soap)(this)).getAllProductsNames(inValue);
            return retVal.Body.getAllProductsNamesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TiendaWebApp.TiendaServiceReference.ExistProductResponse TiendaWebApp.TiendaServiceReference.Service1Soap.ExistProduct(TiendaWebApp.TiendaServiceReference.ExistProductRequest request) {
            return base.Channel.ExistProduct(request);
        }
        
        public bool ExistProduct(string name) {
            TiendaWebApp.TiendaServiceReference.ExistProductRequest inValue = new TiendaWebApp.TiendaServiceReference.ExistProductRequest();
            inValue.Body = new TiendaWebApp.TiendaServiceReference.ExistProductRequestBody();
            inValue.Body.name = name;
            TiendaWebApp.TiendaServiceReference.ExistProductResponse retVal = ((TiendaWebApp.TiendaServiceReference.Service1Soap)(this)).ExistProduct(inValue);
            return retVal.Body.ExistProductResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TiendaWebApp.TiendaServiceReference.getProductIDResponse TiendaWebApp.TiendaServiceReference.Service1Soap.getProductID(TiendaWebApp.TiendaServiceReference.getProductIDRequest request) {
            return base.Channel.getProductID(request);
        }
        
        public string getProductID(string name) {
            TiendaWebApp.TiendaServiceReference.getProductIDRequest inValue = new TiendaWebApp.TiendaServiceReference.getProductIDRequest();
            inValue.Body = new TiendaWebApp.TiendaServiceReference.getProductIDRequestBody();
            inValue.Body.name = name;
            TiendaWebApp.TiendaServiceReference.getProductIDResponse retVal = ((TiendaWebApp.TiendaServiceReference.Service1Soap)(this)).getProductID(inValue);
            return retVal.Body.getProductIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TiendaWebApp.TiendaServiceReference.getProductSellsResponse TiendaWebApp.TiendaServiceReference.Service1Soap.getProductSells(TiendaWebApp.TiendaServiceReference.getProductSellsRequest request) {
            return base.Channel.getProductSells(request);
        }
        
        public TiendaWebApp.TiendaServiceReference.ArrayOfInt getProductSells(string name) {
            TiendaWebApp.TiendaServiceReference.getProductSellsRequest inValue = new TiendaWebApp.TiendaServiceReference.getProductSellsRequest();
            inValue.Body = new TiendaWebApp.TiendaServiceReference.getProductSellsRequestBody();
            inValue.Body.name = name;
            TiendaWebApp.TiendaServiceReference.getProductSellsResponse retVal = ((TiendaWebApp.TiendaServiceReference.Service1Soap)(this)).getProductSells(inValue);
            return retVal.Body.getProductSellsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TiendaWebApp.TiendaServiceReference.getProductAverageSellsResponse TiendaWebApp.TiendaServiceReference.Service1Soap.getProductAverageSells(TiendaWebApp.TiendaServiceReference.getProductAverageSellsRequest request) {
            return base.Channel.getProductAverageSells(request);
        }
        
        public float getProductAverageSells(string name) {
            TiendaWebApp.TiendaServiceReference.getProductAverageSellsRequest inValue = new TiendaWebApp.TiendaServiceReference.getProductAverageSellsRequest();
            inValue.Body = new TiendaWebApp.TiendaServiceReference.getProductAverageSellsRequestBody();
            inValue.Body.name = name;
            TiendaWebApp.TiendaServiceReference.getProductAverageSellsResponse retVal = ((TiendaWebApp.TiendaServiceReference.Service1Soap)(this)).getProductAverageSells(inValue);
            return retVal.Body.getProductAverageSellsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TiendaWebApp.TiendaServiceReference.FormatoCorrectoResponse TiendaWebApp.TiendaServiceReference.Service1Soap.FormatoCorrecto(TiendaWebApp.TiendaServiceReference.FormatoCorrectoRequest request) {
            return base.Channel.FormatoCorrecto(request);
        }
        
        public string FormatoCorrecto(string itemID) {
            TiendaWebApp.TiendaServiceReference.FormatoCorrectoRequest inValue = new TiendaWebApp.TiendaServiceReference.FormatoCorrectoRequest();
            inValue.Body = new TiendaWebApp.TiendaServiceReference.FormatoCorrectoRequestBody();
            inValue.Body.itemID = itemID;
            TiendaWebApp.TiendaServiceReference.FormatoCorrectoResponse retVal = ((TiendaWebApp.TiendaServiceReference.Service1Soap)(this)).FormatoCorrecto(inValue);
            return retVal.Body.FormatoCorrectoResult;
        }
    }
}
